export const permittingQuestions: string[] = [
  "What is the current zoning of this property?",
  "Are there any properties that abut (next to or have a common boundary with) onto this property?",
  "Is my property within 300 feet of another town?",
  "What is the zoning ordinance for this property?",
  "Where are the existing utilities on the property?",
  "What is the current topography of the property?",
  "What is the location of all trees on the property?",
  "What elevation is the property at? Is the property in a floodplain?",
  "Is my property in a historical district?",
  "Is this property in a flood zone?",
  "An application will be considered to result in insignificant traffic impacts on the local roadway network if it is expected to generate less than 20 vehicle trips, ends during the peak hour period, or less than 200 vehicle trips per day.",
  "An application will be considered to significantly impact the local roadway network if it is expected to generate 20 or more vehicle trip ends during the peak hour period or 200 or more vehicle trip ends per day. Applications that result in significant traffic impact will be required to submit a complete traffic impact analysis addressing the site-specific impact on the adjacent roadway network.",
  "What is the total land area of the proposed site?",
  "Can you generate a detailed map of the site, including neighboring properties and key landmarks?",
  "Are there any natural features on the site, such as water bodies or vegetation, that need to be marked on the map?",
  "What is the address and coordinates (latitude and longitude) of the proposed site?",
  "Can you identify nearby amenities such as schools, public transportation, and healthcare facilities?",
  "What is the current zoning classification of the site?",
  "Are there any zoning restrictions or regulations that may impact the development of affordable housing?",
  "Can you provide a map overlay indicating the zoning boundaries in the vicinity?",
  "What are the adjacent properties to the project site, and are there any known environmental issues in the vicinity?",
  "What is the flood risk status of the project site according to the FEMA Flood Insurance Rate Map (FIRM)?",
  "Is radon testing applicable to the project site?",
  "Are there any known or suspected hazardous materials on or near the project site?",
  "What local, state, and federal environmental regulations apply to the project, and how can the development ensure compliance with these regulations?",
  "Are there any potential environmental impacts on the surrounding community, and what measures are in place to mitigate or address these concerns?",
  "Are there potential future environmental risks or considerations that should be taken into account for the long-term sustainability of the affordable housing project?",
];