import { Program } from "./interfaces";

export const WILLOW_COLOR = "#3068cd";
export const WILLOW_COLOR_HOVER = "#1d478f";
export const SECONDARY_COLOR = "#FFFF";
export const DARK_GREY_COLOR = "#333333";

export const OPENAI_ASSISTANT_ID = "asst_LkIZXhCrOK5qaG2APJQJMFbM";

export const programs: Program[] = [
  {
    name: "Affordable Housing Trust Fund",
    level: "City",
    criteria: {
      amiRange: [0, 80],
      adaRange: [0, 10],
      unhoused: false,
      firstTimeHomebuyers: false,
      mixedIncome: false,
      affordabilityTerm: [0, 30],
      constructionStartDate: new Date("2024-12-31"),
      dateOfOccupancyRequired: new Date("2026-09-30"),
    },
    description: "Program for the Affordable Housing Trust Fund.",
    link: "https://www.worcesterma.gov/uploads/e1/6e/e16ee06f7891e370cdedbfc1cde18311/ahtf-application-scoring-guidance.pdf",
  },
  {
    name: "HOME Investment Partnerships Program",
    level: "City & Federal",
    criteria: {
      amiRange: [0, 80],
      adaRange: [0, 0],
      unhoused: false,
      firstTimeHomebuyers: false,
      mixedIncome: false,
      affordabilityTerm: [0, 20],
    },
    description: "Program for HOME Investment Partnerships.",
    link: "https://www.worcesterma.gov/uploads/d5/40/d540113d70884df976490fbed48d0456/home-tbra-rfp-2022.pdf",
  },
  {
    name: "HOME-ARP",
    level: "City",
    criteria: {
      amiRange: [0, 30],
      adaRange: [0, 0],
      unhoused: true,
      firstTimeHomebuyers: false,
      mixedIncome: false,
      affordabilityTerm: [0, 0],
    },
    description: "Program for HOME-ARP.",
  },
  {
    name: "First Time Homeownership Development",
    level: "City",
    criteria: {
      amiRange: [0, 80],
      adaRange: [0, 0],
      unhoused: false,
      firstTimeHomebuyers: true,
      mixedIncome: false,
      affordabilityTerm: [0, 0],
    },
    description: "Program for First Time Homeownership Development.",
    link: "https://www.masshousing.com/en/home-ownership/homebuyers/down-payment-assistance",
  },
  {
    name: "Housing First Solutions",
    level: "City",
    criteria: {
      amiRange: [0, 30],
      adaRange: [0, 0],
      unhoused: true,
      firstTimeHomebuyers: false,
      mixedIncome: false,
      affordabilityTerm: [0, 0],
    },
    description: "Program for Housing First Solutions.",
    link: "https://endhomelessness.org/resource/rapid-re-housing-toolkit/",
  },
  {
    name: "Housing Development Incentive Program / TIE",
    level: "City",
    criteria: {
      amiRange: [0, 0],
      adaRange: [0, 0],
      unhoused: false,
      firstTimeHomebuyers: false,
      mixedIncome: true,
      affordabilityTerm: [0, 0],
    },
    description: "Program for Housing Development Incentive / TIE.",
    link: "https://www.mass.gov/info-details/housing-development-incentive-program-hdip#application-process-",
  },
  {
    name: "Inclusionary Zoning",
    level: "City",
    criteria: {
      amiRange: [60, 80],
      adaRange: [0, 0],
      unhoused: false,
      firstTimeHomebuyers: false,
      mixedIncome: false,
      affordabilityTerm: [0, 0],
    },
    description: "Program for Inclusionary Zoning.",
  },
  {
    name: "DHCD HOME Investment Partnerships Program",
    level: "State",
    criteria: {
      amiRange: [0, 80],
      adaRange: [0, 0],
      unhoused: false,
      firstTimeHomebuyers: false,
      mixedIncome: false,
      affordabilityTerm: [0, 0],
    },
    description: "Program for DHCD HOME Investment Partnerships.",
    link: "https://www.mass.gov/doc/home-hsfprogguidpdf/download",
  },
  {
    name: "Low Income Housing Tax Credits (LIHTC)",
    level: "State",
    criteria: {
      amiRange: [0, 80],
      adaRange: [0, 0],
      unhoused: false,
      firstTimeHomebuyers: false,
      mixedIncome: false,
      affordabilityTerm: [0, 30],
    },
    description: "Program for Low Income Housing Tax Credits (LIHTC).",
    link: "https://www.mass.gov/info-details/low-income-housing-tax-credit-lihtc-0#how-it-works-",
  },
  {
    name: "Housing Stabilization Fund",
    level: "State",
    criteria: {
      amiRange: [0, 80],
      adaRange: [0, 0],
      unhoused: false,
      firstTimeHomebuyers: false,
      mixedIncome: false,
      affordabilityTerm: [0, 40],
    },
    description: "Program for Housing Stabilization Fund.",
    link: "https://www.mass.gov/info-details/housing-stabilization-fund-hsf#eligible-activities-and-affordability-requirements-",
  },
  {
    name: "Affordable Housing Trust Fund",
    level: "State",
    criteria: {
      amiRange: [0, 80],
      adaRange: [0, 0],
      unhoused: false,
      firstTimeHomebuyers: false,
      mixedIncome: false,
      affordabilityTerm: [0, 30],
    },
    description: "Program for the State's Affordable Housing Trust Fund.",
    link: "https://www.masshousing.com/en/developers/new-construction/ahtf",
  },
  {
    name: "Community-Based Housing (Accessibility)",
    level: "State",
    criteria: {
      amiRange: [0, 110],
      adaRange: [0, 0],
      unhoused: false,
      firstTimeHomebuyers: false,
      mixedIncome: false,
      affordabilityTerm: [0, 0],
    },
    description: "Program for Community-Based Housing (Accessibility).",
    link: "https://www.mass.gov/info-details/community-based-housing-cbh",
  },
  {
    name: "Housing Innovations Fund (Special Needs)",
    level: "State",
    criteria: {
      amiRange: [0, 30],
      adaRange: [0, 0],
      unhoused: false,
      firstTimeHomebuyers: false,
      mixedIncome: true,
      affordabilityTerm: [0, 0],
    },
    description: "Program for Housing Innovations Fund (Special Needs).",
    link: "https://www.mass.gov/info-details/housing-innovations-fund-hif#eligible-activities-and-affordability-requirements-",
  },
  {
    name: "Commercial Area Transit Node (CATN) Housing",
    level: "State",
    criteria: {
      amiRange: [0, 0],
      adaRange: [0, 0],
      unhoused: false,
      firstTimeHomebuyers: false,
      mixedIncome: true,
      affordabilityTerm: [0, 0],
    },
    description: "Program for Commercial Area Transit Node (CATN) Housing.",
    link: "https://www.mass.gov/info-details/commercial-area-transit-node-housing-program-catnhp#eligible-activities-and-affordability-requirements-",
  },
  {
    name: "Commonwealth Builders (MassHousing)",
    level: "State",
    criteria: {
      amiRange: [0, 120],
      adaRange: [0, 0],
      unhoused: false,
      firstTimeHomebuyers: true,
      mixedIncome: false,
      affordabilityTerm: [0, 30],
    },
    description: "Program for Commonwealth Builders by MassHousing.",
    link: "https://www.masshousing.com/-/media/Files/Developers/CommonWealth-Builder-Guidelines.ashx",
  },
  {
    name: "Workforce Housing Program (MassHousing)",
    level: "State",
    criteria: {
      amiRange: [0, 120],
      adaRange: [0, 0],
      unhoused: false,
      firstTimeHomebuyers: false,
      mixedIncome: false,
      affordabilityTerm: [15, 40],
    },
    description: "Program for Workforce Housing by MassHousing.",
    link: "https://www.masshousing.com/-/media/Files/Developers/WorkforceHousing_Guidelines.ashx",
  },
];
